package io.quarkus.runner;

import io.quarkus.runtime.Application;

/**
 * W282: Manually created ApplicationImpl for native-image compatibility.
 * Normally generated by the Quarkus build plugin.
 */
public class ApplicationImpl extends Application {
    public ApplicationImpl() {
        super(false);
    }

    @Override
    public String getName() {
        return "io.quarkus.runner.ApplicationImpl";
    }

    @Override
    protected void doStart(String[] args) {
        System.out.println("MATRIX v2.0.0 — native image started");
        System.out.println("Arguments: " + java.util.Arrays.toString(args));
        // Note: This is a minimal native entry-point.
        // For full Quarkus DI + CLI features, use the standard JVM mode:
        //   ./gradlew :matrix-core:quarkusDev
        System.out.println("Use ./gradlew :matrix-core:quarkusRun for full features.");
        // Exit cleanly for now
    }

    @Override
    protected void doStop() {
        // No-op
    }
}
