package io.quarkus.runner;

import io.quarkus.runtime.Application;

/**
 * W285 — Manually created ApplicationImpl for native-image compatibility.
 *
 * <p>Normally generated by the Quarkus build plugin. Minimal version.
 *
 * <p>For full Quarkus DI features, use the standard JVM mode:
 *   ./gradlew :matrix-core:quarkusRun
 *
 * <p>CONSTITUTION VI compliance: native deployment entry-point,
 * not a phenomenal consciousness claim.
 */
public class ApplicationImpl extends Application {
    public ApplicationImpl() {
        super(false);
    }

    @Override
    public String getName() {
        return "io.quarkus.runner.ApplicationImpl";
    }

    @Override
    protected void doStart(String[] args) {
        System.out.println("MATRIX v2.0.0 — native image started (size 126MB, epsilon GC)");
        System.out.println("Arguments: " + java.util.Arrays.toString(args));
        System.out.println("For full Quarkus features use: ./gradlew :matrix-core:quarkusRun");
    }

    @Override
    protected void doStop() {
        // No-op
    }
}
