apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.fullname" . }}-secrets
type: Opaque
stringData:
  stripe-webhook-secret: {{ .Values.secrets.stripeWebhookSecret | quote }}
  license-signing-secret: {{ .Values.secrets.licenseSigningSecret | quote }}
