#!/usr/bin/env python3
"""
ldn2h — .ldn snapshot to C header converter for matrix-micro.

Reads a .ldn JSON snapshot (produced by SnapshotStore.java) and generates
a C header file with MPDTNeuron descriptors + const truth tables, ready
for embedding into ESP32/Arduino firmware.

Usage:
    python3 ldn2h.py snapshot.ldn [output_dir]
    python3 ldn2h.py snapshot.ldn ../firmware/

Output:
    <neuron_name>.h for each neuron in the snapshot.
    matrix_neurons.h — aggregate header with all neurons.
"""

import json
import os
import sys
import uuid


def bitset_from_long_array(long_array, bit_count):
    bits = [False] * bit_count
    for word_idx, word in enumerate(long_array):
        base = word_idx * 64
        for bit in range(64):
            idx = base + bit
            if idx >= bit_count:
                break
            bits[idx] = (word >> bit) & 1 != 0
    return bits


def bits_to_uint32(bits):
    words = []
    total_bits = len(bits)
    num_words = (total_bits + 31) // 32
    for w in range(num_words):
        word = 0
        for b in range(32):
            idx = w * 32 + b
            if idx < total_bits and bits[idx]:
                word |= (1 << b)
        words.append(word)
    return words


def sanitize_c_identifier(name):
    result = []
    for c in name:
        if c.isalnum() or c == '_':
            result.append(c)
        else:
            result.append('_')
    result = ''.join(result)
    if result and result[0].isdigit():
        result = '_' + result
    return result or 'neuron'


def generate_neuron_header(record):
    neuron_id = record["neuronId"]
    k = record["k"]
    truth_bits = record["truthTableBits"]
    state = record.get("state", "STABLE")
    generation = record.get("generation", 0)

    safe_id = sanitize_c_identifier(neuron_id)
    var_name = f"mpdt_{safe_id}"

    bit_count = 1 << k
    bits = bitset_from_long_array(truth_bits, bit_count)
    uint32_words = bits_to_uint32(bits)

    hex_words = []
    for w in uint32_words:
        hex_words.append(f"0x{w:08X}")
    table_str = ", ".join(hex_words)

    header = f"""/* Auto-generated by ldn2h.py — do not edit */
#ifndef MPDT_NEURON_{safe_id.upper()}_H
#define MPDT_NEURON_{safe_id.upper()}_H

#include "mpdt_neuron.h"

static const uint32_t {safe_id}_table[{len(uint32_words)}] = {{ {table_str} }};

static const MPDTNeuron {var_name} = {{
    .k = {k},
    .table = {safe_id}_table
}};

/*
 * Neuron: {neuron_id}
 * Generation: {generation}
 * State: {state}
 * k = {k} inputs, table = {len(uint32_words)} words ({bit_count} bits)
 */

#endif /* MPDT_NEURON_{safe_id.upper()}_H */
"""
    return var_name, header


def generate_aggregate_header(neuron_names, filename_prefix):
    safe_prefix = sanitize_c_identifier(filename_prefix)
    guard = f"MATRIX_NEURONS_{safe_prefix.upper()}_H"

    includes = []
    externs = []
    entries = []
    for i, name in enumerate(neuron_names):
        inc_name = name.replace("mpdt_", "")
        includes.append(f'#include "{inc_name}.h"')
        externs.append(f"extern const MPDTNeuron {name};")
        entries.append(f"    &{name}")

    header = f"""/* Auto-generated by ldn2h.py — do not edit */
#ifndef {guard}
#define {guard}

#include "mpdt_neuron.h"

{chr(10).join(includes)}

#define MATRIX_NEURON_COUNT {len(neuron_names)}

{chr(10).join(externs)}

static const MPDTNeuron *matrix_neurons[MATRIX_NEURON_COUNT] = {{
{','.join(entries)}
}};

#endif /* {guard} */
"""
    return header


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <snapshot.ldn> [output_dir]")
        sys.exit(1)

    ldn_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(ldn_path) or "."

    os.makedirs(output_dir, exist_ok=True)

    with open(ldn_path, "r") as f:
        snapshot = json.load(f)

    neurons = snapshot.get("neurons", [])
    if not neurons:
        print("No neurons found in snapshot")
        sys.exit(1)

    base_name = os.path.splitext(os.path.basename(ldn_path))[0]
    safe_base = sanitize_c_identifier(base_name)

    neuron_names = []
    for record in neurons:
        var_name, header = generate_neuron_header(record)
        neuron_names.append(var_name)

        safe_id = sanitize_c_identifier(record["neuronId"])
        out_path = os.path.join(output_dir, f"{safe_id}.h")
        with open(out_path, "w") as f:
            f.write(header)
        print(f"  Generated: {out_path}")

    agg_header = generate_aggregate_header(neuron_names, safe_base)
    agg_path = os.path.join(output_dir, f"matrix_{safe_base}_neurons.h")
    with open(agg_path, "w") as f:
        f.write(agg_header)
    print(f"  Generated: {agg_path}")

    print(f"\nTotal: {len(neurons)} neurons exported from {ldn_path}")


if __name__ == "__main__":
    main()
