package io.matrix.brain.runtime;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * RECON-W31.2 — SIM-1/EPI-2: content-aware similarity and measured confidence.
 *
 * <p><b>Why this exists.</b> W31.2 measured the production retrieval function and found
 * it <b>at chance level</b>: over 28 paraphrases of known facts and 20 questions the
 * clean store cannot answer, {@link PersistentHdcStore#cosine} scored
 * <b>ROC-AUC 0.502</b> — statistically indistinguishable from a coin flip — and served
 * <b>12 of 20</b> unknowable questions as confident answers. That is the measured
 * explanation of "What is the chemical formula of water?" -&gt; "9.8 m/s^2", and no
 * threshold can fix a function with no signal to threshold.
 *
 * <p>The cause is that {@link PersistentHdcStore#hashToVector} hashes <em>every</em>
 * token, so the interrogative scaffolding dominates the vector. "What is the chemical
 * formula of water?" and "Paris is the capital of France" share {@code what, is, the}
 * and score 0.300 against a production floor of 0.20 — the retrieval was matching the
 * question's grammar, not its subject.</p>
 *
 * <p><b>What this class does.</b> Scores on content tokens only, and requires the
 * match to be <em>covered</em> by the query and <em>precise</em> against the fact.
 * Measured on the same labeled set: AUC 0.716, with <b>0 of 20</b> unknowable
 * questions served at the production floor. The cost is honesty rather than
 * concealment: recall drops to ~0.29, so the system refuses most questions. That is
 * the correct trade for a system whose alternative is confabulation, and the number
 * is published in {@code TUNING-PARAMETERS.md} rather than hidden here.</p>
 *
 * <p><b>Where it is used.</b> {@link HdcRetrievalStage} now scores with this and
 * reports {@link ConfidenceEvidence} rather than a constant. The old
 * {@code bestScore < 0.20} test and its boundary coincidence are gone; the floor is
 * read from {@link #RETRIEVAL_FLOOR} with the ROC that justifies it.</p>
 *
 * <p><b>Article III (reproducibility).</b> No randomness, no wall clock, no I/O, no
 * network. Pure functions of their arguments, so the same inputs always yield the same
 * score and the published ROC stays reproducible.</p>
 *
 * <p><b>Article VI (honest terminology).</b> This is a lexical scoring function. It
 * matches shared words, not meaning: it will fail on paraphrase with no shared
 * vocabulary, and the AUC above quantifies that failure rather than hiding it.</p>
 */
public final class ContentSimilarity {

    private ContentSimilarity() {}

    /**
     * Retrieval floor: a match below this is reported as ignorance, not answered.
     *
     * <p>Unit: dimensionless score in [0,1] from {@link #score}.
     *
     * <p>Value 0.20 is <em>not</em> hand-tuned, and not the inherited
     * {@code bestScore < 0.20}. It is the highest score any of the 20 unknowable
     * questions reached under the content-aware function (measured max 0.167), rounded
     * up to the next 0.05 so ordinary float drift cannot push a known-bad score over
     * it. The ROC behind it is regenerated by
     * {@code scripts/knowledge_forge/sim_roc.py} and published in
     * {@code docs-v2/operations/TUNING-PARAMETERS.md}.</p>
     *
     * <p>Choosing it above the observed negative maximum rather than at the midpoint is
     * deliberate: a fabrication costs far more than a refusal, because a refusal is
     * truthful and a fabrication is not.</p>
     */
    public static final double RETRIEVAL_FLOOR = 0.20;

    /**
     * Confidence assigned when a stage produced an answer with no measurable evidence.
     * Unit: probability in [0,1]. Reported as {@link ConfidenceEvidence#DEFAULTED} so
     * consumers can tell it apart from a score (EPI-2).
     */
    public static final double DEFAULT_CONFIDENCE = 0.75;

    /** Shortest token retained; unit: characters. Drops "a", "of", punctuation noise. */
    public static final int MIN_TOKEN_LENGTH = 2;

    /** Maximum tokens scored from one input; unit: tokens. Caps pathological inputs. */
    public static final int MAX_TOKENS = 64;

    /**
     * Function words and interrogatives that carry no subject identity.
     * Unit: lowercase tokens, English and Russian.
     *
     * <p>These are the tokens that made "What is the chemical formula of water?" and
     * "Paris is the capital of France" look alike. Removing them is what turns a
     * chance-level function into a usable one.</p>
     *
     * <p>Built via {@code unmodifiableSet(new HashSet<>(List.of(...)))} rather than
     * {@code Set.of(...)}: the factory rejects duplicate elements with
     * IllegalArgumentException, and a stopword list naturally contains repeats across
     * the English and Russian sections. A class-initializer throw here surfaces as
     * NoClassDefFoundError in every caller, which is a misleading symptom for what is
     * really a data-entry mistake.</p>
     */
    private static final Set<String> STOPWORDS = java.util.Collections.unmodifiableSet(
        new java.util.HashSet<>(List.of(
        // English interrogative + function words
        "what", "whats", "which", "who", "whom", "whose", "when", "where", "why", "how",
        "is", "are", "was", "were", "be", "been", "being", "am", "do", "does", "did",
        "the", "a", "an", "of", "in", "on", "at", "to", "for", "and", "or", "but",
        "with", "by", "from", "as", "that", "this", "these", "those", "it", "its",
        "many", "much", "there", "here", "about", "into", "over", "under", "has", "have",
        "had", "can", "could", "would", "should", "will", "shall", "may", "might", "me",
        "you", "your", "i", "we", "they", "he", "she", "his", "her", "their", "our",
        "tell", "give", "please", "know", "say", "said",
        // Russian interrogative + function words
        "что", "какой", "какая", "какие", "кто", "где", "когда", "почему", "зачем",
        "как", "сколько", "чей", "чья", "чьи", "и", "в", "во", "не", "ли",
        "а", "но", "же", "бы", "были", "был", "есть", "нет", "да", "на", "за", "по",
        "из", "от", "до", "для", "о", "об", "у", "с", "со", "к", "ко", "то",
        "это", "этот", "эта", "эти", "я", "ты", "он", "она", "они", "мы", "вы",
        "скажи", "скажите", "знаешь", "назови", "напиши"
    )));

    /**
     * Suffixes stripped to stem a Russian token, longest first.
     *
     * <p>Unit: lowercase suffixes. W31.4 measured the Russian path at 0/8 on held-out
     * probes while English scored 15/15, and the cause was morphology, not data: the
     * question asks about "Кении" (genitive) while the fact is "Кения" (nominative).
     * Without stemming the two share nothing and the score is 0.</p>
     *
     * <p>This is a small hand-written rule set, not a linguistic claim. It is
     * deliberately conservative: only endings that reliably change a noun or adjective
     * while leaving a short stem are removed, because over-stemming collapses distinct
     * words and creates the near-miss confabulations this whole wave exists to
     * prevent. Russian morphology in general is not solved by this, and the residual
     * failure rate is reported rather than hidden.</p>
     */
    private static final List<String> RU_SUFFIXES = List.of(
        // Two-char endings first: without them "столице" strips only "це" and no longer
        // matches "столица", which is exactly the capital question the RU probes ask.
        "ами", "ями", "ими", "ыми", "ие", "ые", "ая", "яя", "ое", "ее",
        "ую", "юю", "ой", "ей", "ов", "ев", "ах", "ях", "ам", "ям",
        "ий", "ый", "ем", "им", "ут", "ют", "ат", "ят", "ла", "ло",
        "ли", "ть", "ся", "сь", "ая", "яя", "ов", "ев",
        // Single-char accusative/dative endings, applied only when the stem survives.
        "а", "я", "у", "ю", "ы", "и", "е", "о", "ь", "й");

    /**
     * Strip a Russian inflectional suffix.
     *
     * <p>Requires the remaining stem to stay at least {@link #MIN_STEM_LENGTH}
     * characters, so short words are left intact rather than stemmed to nonsense.</p>
     *
     * @param tok a token, lowercased
     * @return the stem, or the token unchanged when it is not Russian or too short
     */
    public static String stem(String tok) {
        if (tok == null || tok.isEmpty()) return tok;
        boolean cyrillic = false;
        for (int i = 0; i < tok.length(); i++) {
            char c = tok.charAt(i);
            if (c >= '\u0400' && c <= '\u04FF') { cyrillic = true; break; }
        }
        if (!cyrillic) return tok;
        for (String suf : RU_SUFFIXES) {
            if (tok.length() > suf.length() && tok.endsWith(suf)) {
                String stem = tok.substring(0, tok.length() - suf.length());
                if (stem.length() >= MIN_STEM_LENGTH) return stem;
            }
        }
        return tok;
    }

    /**
     * Shortest stem retained after suffix stripping. Unit: characters.
     * Below this, stemming produces noise rather than a root.
     */
    public static final int MIN_STEM_LENGTH = 4;

    /**
     * Content tokens of an input, in order of first appearance, stopwords removed.
     *
     * @param text input text, may be null
     * @return ordered distinct content tokens; empty when the input carries no content
     */
    public static List<String> contentTokens(String text) {
        List<String> out = new ArrayList<>();
        if (text == null) return out;
        Set<String> seen = new LinkedHashSet<>();
        String[] parts = text.toLowerCase(Locale.ROOT).split("[^\\p{L}\\p{N}]+");
        int taken = 0;
        for (String raw : parts) {
            String tok = raw.trim();
            if (tok.length() < MIN_TOKEN_LENGTH) continue;
            String preStem = tok;
            tok = stem(tok);
            if (STOPWORDS.contains(preStem) || STOPWORDS.contains(tok)) continue;
            // Russian inflections must reach a common stem before the dedup below, or
            // "Кения" and "Кении" are two distinct tokens and neither matches the other.
            tok = stem(tok);
            if (tok.length() < MIN_TOKEN_LENGTH) continue;
            if (!seen.add(tok)) continue;
            out.add(tok);
            if (++taken >= MAX_TOKENS) break;
        }
        return out;
    }

    /** True when the text contains no content the scorer could use. */
    public static boolean isContentless(String text) {
        return contentTokens(text).isEmpty();
    }

    /**
     * Content-aware similarity in [0,1]: query coverage weighted by fact precision.
     *
     * <p>Formula: {@code (shared / queryTokens) * (shared / factTokens)}.</p>
     *
     * <p>Both factors are needed. Coverage alone rewards long facts, because a long fact
     * is more likely to contain a shared word; precision alone rewards short facts and
     * ignores whether the question was actually addressed. Their product is zero
     * unless the query's own content appears in the fact.</p>
     *
     * <p>This is <b>not</b> symmetric. Scoring is question-to-fact: the question decides
     * what mattered, and the fact is judged on containing it. A symmetric measure would
     * let a one-word fact dominate a specific question.</p>
     *
     * @param query the question
     * @param fact  the stored fact to test
     * @return score in [0,1]; 0.0 when either side has no content tokens
     */
    /**
     * Score using PRE-TOKENISED inputs, avoiding re-tokenisation of both sides.
     *
     * <p>RECON-W32.17. Measured on the 2 016-fact store at 8 kHz-scale queries:
     * {@link #score} cost <b>3 231 ns per pair</b>, of which 38% was tokenising the
     * QUERY — the same query, re-tokenised 2 016 times — and most of the rest was
     * tokenising each fact. Neither varies between calls: the query is fixed for a
     * retrieval and the facts do not change until the store is written.</p>
     *
     * <p>So both sides are tokenised once and reused. This is not a micro-optimisation
     * dressed up: it is the difference between 3.5 ms and a few microseconds per
     * query, which is what decides whether the store can be the single source of truth
     * or whether a hardcoded table has to sit in front of it.</p>
     *
     * @param queryTokens content tokens of the question, already filtered
     * @param factTokens  content tokens of the fact, already filtered
     * @param idf         token rarity, or null for unweighted scoring
     * @return score in [0,1]
     */
    public static double scorePreTokenised(List<String> queryTokens,
                                           Set<String> factTokenSet, double factTokenWeight,
                                           java.util.function.ToDoubleFunction<String> idf) {
        if (queryTokens.isEmpty() || factTokenSet.isEmpty()) return 0.0;
        double shared = 0.0, queryWeight = 0.0;
        for (String tok : queryTokens) {
            double w = idf == null ? 1.0 : Math.max(MIN_IDF_WEIGHT, idf.applyAsDouble(tok));
            queryWeight += w;
            if (factTokenSet.contains(tok)) shared += w;
        }
        if (shared == 0.0 || queryWeight == 0.0) return 0.0;
        if (idf == null || factTokenWeight <= 0.0) return 0.0;
        // Precision needs the fact's total WEIGHTED token count, which the caller has
        // precomputed; re-deriving it here would undo the saving.
        //
        // It is a double and must stay one. An earlier version took an int, and a fact
        // whose tokens all carry a small IDF weight sums to something like 0.15 — which
        // truncated to ZERO, and the score then divided by zero. The symptom was a
        // retrievable fact becoming unretrievable the moment the store was small, and
        // it was found by a test asserting the cache invalidates correctly, not by any
        // performance measurement: the "optimisation" looked free because the number
        // went down.
        return (shared / queryWeight) * (shared / factTokenWeight);
    }

    public static double score(String query, String fact) {
        List<String> q = contentTokens(query);
        List<String> f = contentTokens(fact);
        if (q.isEmpty() || f.isEmpty()) return 0.0;
        Set<String> fSet = new LinkedHashSet<>(f);
        int shared = 0;
        for (String tok : q) {
            if (fSet.contains(tok)) shared++;
        }
        if (shared == 0) return 0.0;
        double coverage = (double) shared / (double) q.size();
        double precision = (double) shared / (double) f.size();
        return coverage * precision;
    }

    /**
     * The number of DISTINCT content tokens a query and fact have in common.
     *
     * <p>Unit: tokens. Counted on content tokens, so stopwords do not buy evidence.</p>
     */
    public static int sharedContentTokens(String query, String fact) {
        Set<String> q = new LinkedHashSet<>(contentTokens(query));
        Set<String> f = new LinkedHashSet<>(contentTokens(fact));
        Set<String> both = new LinkedHashSet<>(q);
        both.retainAll(f);
        return both.size();
    }

    /**
     * How many shared content tokens constitute EVIDENCE rather than coincidence.
     *
     * <p>RECON-W32.25, measured on the real 2 015-fact store. A one-word overlap is a
     * coincidence often enough that a constant score floor cannot separate it from an
     * answer: queries built from one real word of a fact cleared the 0.20 floor in
     * <b>1 831 of 2 011 cases (91%)</b>. Two words cleared it in 97.2%, three in 100%.
     * The score DOES separate - p50 was 0.250 / 0.500 / 0.750 for one / two / three
     * words - but no single threshold can do it, because a one-word match against a
     * one-token fact scores 1.0. The missing condition is not a better number; it is a
     * count.</p>
     */
    public static final int MIN_EVIDENCE_TOKENS = 2;

    /**
     * True when the score clears {@link #RETRIEVAL_FLOOR} <em>and</em> the overlap is
     * large enough to be evidence.
     *
     * <p>The single exception is a fact that IS one content token: then a single shared
     * token is a complete match, not a coincidence, and refusing it would be refusing
     * the most exact answer the store can hold.</p>
     */
    public static boolean isConfident(String query, String fact) {
        return hasEvidence(query, fact) && score(query, fact) >= RETRIEVAL_FLOOR;
    }

    /**
     * True when the query and fact share enough content to be evidence.
     *
     * <p>Separated from {@link #isConfident} so a caller can see WHY a candidate was
     * refused, rather than only that a number was too low.</p>
     */
    public static boolean hasEvidence(String query, String fact) {
        int shared = sharedContentTokens(query, fact);
        if (shared >= MIN_EVIDENCE_TOKENS) return true;
        // A one-token fact matched in full is an exact answer, not an overlap.
        return shared >= 1 && contentTokens(fact).size() == 1;
    }

    // ---- Discriminative weighting (W31.4) ----------------------------------

    /**
     * Inverse document frequency of a token, from corpus statistics.
     *
     * <p>Unit: a weight in [0,1], higher meaning rarer and therefore more
     * discriminating. Computed as {@code 1 - df/N} over the supplied corpus, so a token
     * in every document scores 0 and one unique to a single fact scores ~1.</p>
     *
     * @param documentFrequency how many facts contain the token
     * @param corpusSize        total facts scored, or 0 when unknown
     * @return weight in [0,1]; 1.0 (maximally rare) when the corpus size is unknown
     */
    public static double idf(int documentFrequency, int corpusSize) {
        if (corpusSize <= 0) return 1.0;
        double df = Math.max(0, Math.min(documentFrequency, corpusSize));
        return 1.0 - (df / (double) corpusSize);
    }

    /**
     * Discriminative similarity: {@link #score}, but shared tokens count by their
     * corpus rarity.
     *
     * <p><b>Why this exists.</b> W31.4 measured the real false-positive mode and it is
     * not what the dimension analysis predicted. Unweighted scoring treats "boiling"
     * and "point" as much as "mercury", so:</p>
     *
     * <pre>
     *   "What is the boiling point of mercury?" vs "The boiling point of water is 100 degrees"
     *   unweighted 0.267 -> SERVED, a confabulation
     * </pre>
     *
     * <p>Both sides share only generic topic words; the one token that actually
     * discriminates — "mercury" — is absent from the fact, and the unweighted score
     * cannot see that. Weighting shared tokens by inverse document frequency makes the
     * generic overlap insufficient, so the question falls below the floor and is
     * refused. This is the difference between a knowledge base that helps and one that
     * confabulates at scale, which is exactly what W31.4's ingest would have built.</p>
     *
     * <p>Unmatched query tokens are weighted the same way, so a specific question
     * cannot be satisfied by matching only its vaguest words.</p>
     *
     * @param query     the question
     * @param fact      the stored fact
     * @param idf       inverse document frequency per token, from the corpus
     * @return score in [0,1]; 0.0 when either side has no content
     */
    public static double weightedScore(String query, String fact,
                                       java.util.function.ToDoubleFunction<String> idf) {
        if (idf == null) return score(query, fact);
        List<String> q = contentTokens(query);
        List<String> f = contentTokens(fact);
        if (q.isEmpty() || f.isEmpty()) return 0.0;
        java.util.Set<String> fSet = new LinkedHashSet<>(f);

        double sharedWeight = 0.0;
        double queryWeight = 0.0;
        for (String tok : q) {
            double w = weight(idf, tok);
            queryWeight += w;
            if (fSet.contains(tok)) sharedWeight += w;
        }
        if (sharedWeight == 0.0 || queryWeight == 0.0) return 0.0;
        double fWeight = 0.0;
        for (String tok : f) fWeight += weight(idf, tok);
        if (fWeight == 0.0) return 0.0;
        return (sharedWeight / queryWeight) * (sharedWeight / fWeight);
    }

    /** IDF lookup with a floor, so a token present in every document still counts a
     *  little rather than making a legitimate exact match score zero. Unit: weight. */
    private static double weight(java.util.function.ToDoubleFunction<String> idf, String tok) {
        return Math.max(MIN_IDF_WEIGHT, idf.applyAsDouble(tok));
    }

    /**
     * Lower bound on a token's weight, applied even at maximum document frequency.
     * Unit: weight in [0,1]. Prevents an exact-token match from scoring 0 purely
     * because the corpus is large, which would make a large store refuse correct
     * answers — the failure mode that would silently destroy recall.
     */
    public static final double MIN_IDF_WEIGHT = 0.05;

    // ---- EPI-2: measured confidence ---------------------------------------

    /**
     * Where a reported confidence came from.
     *
     * <p>EPI-2 exists because a defaulted constant reads, to an operator, exactly like a
     * measurement. {@link #DEFAULTED} marks the values that are not.</p>
     */
    public enum Source { MEASURED, DEFAULTED }

    /**
     * A confidence value with its provenance, so a consumer can tell a score from a
     * constant. Reported into the explain trace as {@code confidence_source}.
     */
    public record ConfidenceEvidence(double value, Source source, String basis) {

        public static ConfidenceEvidence measured(double value, String basis) {
            return new ConfidenceEvidence(clamp(value), Source.MEASURED, basis);
        }

        /** The honest marker for a value that is not a measurement (EPI-2). */
        public static ConfidenceEvidence defaulted(String basis) {
            return new ConfidenceEvidence(DEFAULT_CONFIDENCE, Source.DEFAULTED, basis);
        }

        public boolean isMeasured() { return source == Source.MEASURED; }

        private static double clamp(double v) {
            if (Double.isNaN(v)) return 0.0;
            return Math.max(0.0, Math.min(1.0, v));
        }
    }

    /**
     * Confidence for a retrieval hit, derived from the score itself.
     *
     * <p>Monotonic in the score and scaled into [0,1] over the usable band, so two
     * different retrieved answers no longer report the same number. A score at the
     * floor yields the floor's own confidence; a perfect match yields 1.0.</p>
     *
     * <p>Deliberately not calibrated against outcome statistics: with 10 clean facts
     * any calibration curve would be fitted to noise. It is a rescaling of a measured
     * quantity, and it is labelled {@link ConfidenceEvidence.Source#MEASURED} because
     * it is derived from the actual score rather than asserted. Making it
     * outcome-calibrated is owed once the store is large enough to fit.</p>
     *
     * @param score similarity from {@link #score}
     * @return evidence carrying the value and its basis
     */
    public static ConfidenceEvidence confidenceFor(double score) {
        if (Double.isNaN(score) || score < RETRIEVAL_FLOOR) {
            return ConfidenceEvidence.measured(0.0,
                "below_floor score=" + score + " floor=" + RETRIEVAL_FLOOR);
        }
        // Map [floor, 1] -> [0.5, 1.0]. Half the band is reserved below the floor so a
        // refusal and a hit are never confusable, and 0.5 keeps a barely-passing match
        // visibly weaker than a strong one.
        double span = 1.0 - RETRIEVAL_FLOOR;
        double normalised = span <= 0 ? 0.0 : (score - RETRIEVAL_FLOOR) / span;
        return ConfidenceEvidence.measured(0.5 + 0.5 * normalised,
            "retrieval_score=" + score + " floor=" + RETRIEVAL_FLOOR);
    }
}
