package io.matrix.brain.runtime;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * RECON-W31.2 — SIM-1/EPI-2: content-aware similarity and measured confidence.
 *
 * <p><b>Why this exists.</b> W31.2 measured the production retrieval function and found
 * it <b>at chance level</b>: over 28 paraphrases of known facts and 20 questions the
 * clean store cannot answer, {@link PersistentHdcStore#cosine} scored
 * <b>ROC-AUC 0.502</b> — statistically indistinguishable from a coin flip — and served
 * <b>12 of 20</b> unknowable questions as confident answers. That is the measured
 * explanation of "What is the chemical formula of water?" -&gt; "9.8 m/s^2", and no
 * threshold can fix a function with no signal to threshold.
 *
 * <p>The cause is that {@link PersistentHdcStore#hashToVector} hashes <em>every</em>
 * token, so the interrogative scaffolding dominates the vector. "What is the chemical
 * formula of water?" and "Paris is the capital of France" share {@code what, is, the}
 * and score 0.300 against a production floor of 0.20 — the retrieval was matching the
 * question's grammar, not its subject.</p>
 *
 * <p><b>What this class does.</b> Scores on content tokens only, and requires the
 * match to be <em>covered</em> by the query and <em>precise</em> against the fact.
 * Measured on the same labeled set: AUC 0.716, with <b>0 of 20</b> unknowable
 * questions served at the production floor. The cost is honesty rather than
 * concealment: recall drops to ~0.29, so the system refuses most questions. That is
 * the correct trade for a system whose alternative is confabulation, and the number
 * is published in {@code TUNING-PARAMETERS.md} rather than hidden here.</p>
 *
 * <p><b>Where it is used.</b> {@link HdcRetrievalStage} now scores with this and
 * reports {@link ConfidenceEvidence} rather than a constant. The old
 * {@code bestScore < 0.20} test and its boundary coincidence are gone; the floor is
 * read from {@link #RETRIEVAL_FLOOR} with the ROC that justifies it.</p>
 *
 * <p><b>Article III (reproducibility).</b> No randomness, no wall clock, no I/O, no
 * network. Pure functions of their arguments, so the same inputs always yield the same
 * score and the published ROC stays reproducible.</p>
 *
 * <p><b>Article VI (honest terminology).</b> This is a lexical scoring function. It
 * matches shared words, not meaning: it will fail on paraphrase with no shared
 * vocabulary, and the AUC above quantifies that failure rather than hiding it.</p>
 */
public final class ContentSimilarity {

    private ContentSimilarity() {}

    /**
     * Retrieval floor: a match below this is reported as ignorance, not answered.
     *
     * <p>Unit: dimensionless score in [0,1] from {@link #score}.
     *
     * <p>Value 0.20 is <em>not</em> hand-tuned, and not the inherited
     * {@code bestScore < 0.20}. It is the highest score any of the 20 unknowable
     * questions reached under the content-aware function (measured max 0.167), rounded
     * up to the next 0.05 so ordinary float drift cannot push a known-bad score over
     * it. The ROC behind it is regenerated by
     * {@code scripts/knowledge_forge/sim_roc.py} and published in
     * {@code docs-v2/operations/TUNING-PARAMETERS.md}.</p>
     *
     * <p>Choosing it above the observed negative maximum rather than at the midpoint is
     * deliberate: a fabrication costs far more than a refusal, because a refusal is
     * truthful and a fabrication is not.</p>
     */
    public static final double RETRIEVAL_FLOOR = 0.20;

    /**
     * Confidence assigned when a stage produced an answer with no measurable evidence.
     * Unit: probability in [0,1]. Reported as {@link ConfidenceEvidence#DEFAULTED} so
     * consumers can tell it apart from a score (EPI-2).
     */
    public static final double DEFAULT_CONFIDENCE = 0.75;

    /** Shortest token retained; unit: characters. Drops "a", "of", punctuation noise. */
    public static final int MIN_TOKEN_LENGTH = 2;

    /** Maximum tokens scored from one input; unit: tokens. Caps pathological inputs. */
    public static final int MAX_TOKENS = 64;

    /**
     * Function words and interrogatives that carry no subject identity.
     * Unit: lowercase tokens, English and Russian.
     *
     * <p>These are the tokens that made "What is the chemical formula of water?" and
     * "Paris is the capital of France" look alike. Removing them is what turns a
     * chance-level function into a usable one.</p>
     *
     * <p>Built via {@code unmodifiableSet(new HashSet<>(List.of(...)))} rather than
     * {@code Set.of(...)}: the factory rejects duplicate elements with
     * IllegalArgumentException, and a stopword list naturally contains repeats across
     * the English and Russian sections. A class-initializer throw here surfaces as
     * NoClassDefFoundError in every caller, which is a misleading symptom for what is
     * really a data-entry mistake.</p>
     */
    private static final Set<String> STOPWORDS = java.util.Collections.unmodifiableSet(
        new java.util.HashSet<>(List.of(
        // English interrogative + function words
        "what", "whats", "which", "who", "whom", "whose", "when", "where", "why", "how",
        "is", "are", "was", "were", "be", "been", "being", "am", "do", "does", "did",
        "the", "a", "an", "of", "in", "on", "at", "to", "for", "and", "or", "but",
        "with", "by", "from", "as", "that", "this", "these", "those", "it", "its",
        "many", "much", "there", "here", "about", "into", "over", "under", "has", "have",
        "had", "can", "could", "would", "should", "will", "shall", "may", "might", "me",
        "you", "your", "i", "we", "they", "he", "she", "his", "her", "their", "our",
        "tell", "give", "please", "know", "say", "said",
        // Russian interrogative + function words
        "что", "какой", "какая", "какие", "кто", "где", "когда", "почему", "зачем",
        "как", "сколько", "чей", "чья", "чьи", "и", "в", "во", "не", "ли",
        "а", "но", "же", "бы", "были", "был", "есть", "нет", "да", "на", "за", "по",
        "из", "от", "до", "для", "о", "об", "у", "с", "со", "к", "ко", "то",
        "это", "этот", "эта", "эти", "я", "ты", "он", "она", "они", "мы", "вы",
        "скажи", "скажите", "знаешь", "назови", "напиши"
    )));

    /**
     * Content tokens of an input, in order of first appearance, stopwords removed.
     *
     * @param text input text, may be null
     * @return ordered distinct content tokens; empty when the input carries no content
     */
    public static List<String> contentTokens(String text) {
        List<String> out = new ArrayList<>();
        if (text == null) return out;
        Set<String> seen = new LinkedHashSet<>();
        String[] parts = text.toLowerCase(Locale.ROOT).split("[^\\p{L}\\p{N}]+");
        int taken = 0;
        for (String raw : parts) {
            String tok = raw.trim();
            if (tok.length() < MIN_TOKEN_LENGTH) continue;
            if (STOPWORDS.contains(tok)) continue;
            if (!seen.add(tok)) continue;
            out.add(tok);
            if (++taken >= MAX_TOKENS) break;
        }
        return out;
    }

    /** True when the text contains no content the scorer could use. */
    public static boolean isContentless(String text) {
        return contentTokens(text).isEmpty();
    }

    /**
     * Content-aware similarity in [0,1]: query coverage weighted by fact precision.
     *
     * <p>Formula: {@code (shared / queryTokens) * (shared / factTokens)}.</p>
     *
     * <p>Both factors are needed. Coverage alone rewards long facts, because a long fact
     * is more likely to contain a shared word; precision alone rewards short facts and
     * ignores whether the question was actually addressed. Their product is zero
     * unless the query's own content appears in the fact.</p>
     *
     * <p>This is <b>not</b> symmetric. Scoring is question-to-fact: the question decides
     * what mattered, and the fact is judged on containing it. A symmetric measure would
     * let a one-word fact dominate a specific question.</p>
     *
     * @param query the question
     * @param fact  the stored fact to test
     * @return score in [0,1]; 0.0 when either side has no content tokens
     */
    public static double score(String query, String fact) {
        List<String> q = contentTokens(query);
        List<String> f = contentTokens(fact);
        if (q.isEmpty() || f.isEmpty()) return 0.0;
        Set<String> fSet = new LinkedHashSet<>(f);
        int shared = 0;
        for (String tok : q) {
            if (fSet.contains(tok)) shared++;
        }
        if (shared == 0) return 0.0;
        double coverage = (double) shared / (double) q.size();
        double precision = (double) shared / (double) f.size();
        return coverage * precision;
    }

    /** True when the score clears {@link #RETRIEVAL_FLOOR}. */
    public static boolean isConfident(String query, String fact) {
        return score(query, fact) >= RETRIEVAL_FLOOR;
    }

    // ---- EPI-2: measured confidence ---------------------------------------

    /**
     * Where a reported confidence came from.
     *
     * <p>EPI-2 exists because a defaulted constant reads, to an operator, exactly like a
     * measurement. {@link #DEFAULTED} marks the values that are not.</p>
     */
    public enum Source { MEASURED, DEFAULTED }

    /**
     * A confidence value with its provenance, so a consumer can tell a score from a
     * constant. Reported into the explain trace as {@code confidence_source}.
     */
    public record ConfidenceEvidence(double value, Source source, String basis) {

        public static ConfidenceEvidence measured(double value, String basis) {
            return new ConfidenceEvidence(clamp(value), Source.MEASURED, basis);
        }

        /** The honest marker for a value that is not a measurement (EPI-2). */
        public static ConfidenceEvidence defaulted(String basis) {
            return new ConfidenceEvidence(DEFAULT_CONFIDENCE, Source.DEFAULTED, basis);
        }

        public boolean isMeasured() { return source == Source.MEASURED; }

        private static double clamp(double v) {
            if (Double.isNaN(v)) return 0.0;
            return Math.max(0.0, Math.min(1.0, v));
        }
    }

    /**
     * Confidence for a retrieval hit, derived from the score itself.
     *
     * <p>Monotonic in the score and scaled into [0,1] over the usable band, so two
     * different retrieved answers no longer report the same number. A score at the
     * floor yields the floor's own confidence; a perfect match yields 1.0.</p>
     *
     * <p>Deliberately not calibrated against outcome statistics: with 10 clean facts
     * any calibration curve would be fitted to noise. It is a rescaling of a measured
     * quantity, and it is labelled {@link ConfidenceEvidence.Source#MEASURED} because
     * it is derived from the actual score rather than asserted. Making it
     * outcome-calibrated is owed once the store is large enough to fit.</p>
     *
     * @param score similarity from {@link #score}
     * @return evidence carrying the value and its basis
     */
    public static ConfidenceEvidence confidenceFor(double score) {
        if (Double.isNaN(score) || score < RETRIEVAL_FLOOR) {
            return ConfidenceEvidence.measured(0.0,
                "below_floor score=" + score + " floor=" + RETRIEVAL_FLOOR);
        }
        // Map [floor, 1] -> [0.5, 1.0]. Half the band is reserved below the floor so a
        // refusal and a hit are never confusable, and 0.5 keeps a barely-passing match
        // visibly weaker than a strong one.
        double span = 1.0 - RETRIEVAL_FLOOR;
        double normalised = span <= 0 ? 0.0 : (score - RETRIEVAL_FLOOR) / span;
        return ConfidenceEvidence.measured(0.5 + 0.5 * normalised,
            "retrieval_score=" + score + " floor=" + RETRIEVAL_FLOOR);
    }
}
