package io.matrix.cli;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * W444 — Docker Build Helper CLI.
 * 
 * Generates a Dockerfile and docker-compose.yml for deploying the
 * conversation stack as a container.
 * 
 * Usage:
 *   java io.matrix.cli.ConversationDocker [output-dir]
 *   Default: docker/
 */
public final class ConversationDocker {
    
    private static final String DEFAULT_OUTPUT_DIR = "docker";
    
    public static void main(String[] args) throws IOException {
        Path outDir = Paths.get(args.length > 0 ? args[0] : DEFAULT_OUTPUT_DIR);
        Files.createDirectories(outDir);
        
        // Generate Dockerfile
        String dockerfile = String.join("\n",
            "# Auto-generated by ConversationDocker CLI (W444)",
            "# Build: docker build -t matrix-conv .",
            "# Run:   docker run -p 9093:9093 matrix-conv",
            "",
            "FROM eclipse-temurin:21-jre-jammy",
            "",
            "LABEL maintainer=\"MATRIX Project\"",
            "LABEL description=\"MATRIX conversation stack with local Qwen2.5-0.5B\"",
            "",
            "WORKDIR /app",
            "",
            "# Copy the built JAR",
            "COPY build/libs/matrix-core-1.0.0.jar /app/matrix-core.jar",
            "",
            "# Copy Qwen model files",
            "COPY models/onnx/qwen05b /app/models/onnx/qwen05b",
            "",
            "# Create data dir",
            "RUN mkdir -p /app/data/conversations",
            "",
            "# Expose ports",
            "EXPOSE 9093 9094 9095",
            "",
            "# Health check",
            "HEALTHCHECK --interval=30s --timeout=3s \\",
            "  CMD wget -qO- http://localhost:9093/health || exit 1",
            "",
            "# Default command runs HTTP server",
            "ENTRYPOINT [\"java\", \"-cp\", \"matrix-core.jar:/app/*\", \"io.matrix.cli.RealConversationServer\", \"9093\"]",
            ""
        );
        Files.writeString(outDir.resolve("Dockerfile"), dockerfile);
        
        // Generate docker-compose.yml
        String compose = String.join("\n",
            "# Auto-generated by ConversationDocker CLI (W444)",
            "# Run:    docker compose up",
            "# Stop:   docker compose down",
            "# Logs:   docker compose logs -f",
            "",
            "version: '3.8'",
            "services:",
            "  matrix-conv:",
            "    build: .",
            "    image: matrix-conv:latest",
            "    container_name: matrix-conv",
            "    ports:",
            "      - \"9093:9093\"  # HTTP REST + Web UI",
            "      - \"9094:9094\"  # Streaming SSE",
            "      - \"9095:9095\"  # Test/eval",
            "    environment:",
            "      - JAVA_OPTS=-Xmx2g",
            "      - MATRIX_MODEL_PATH=/app/models/onnx/qwen05b",
            "    volumes:",
            "      - conv-data:/app/data/conversations",
            "      - conv-backup:/backup",
            "    restart: unless-stopped",
            "",
            "volumes:",
            "  conv-data:",
            "  conv-backup:",
            ""
        );
        Files.writeString(outDir.resolve("docker-compose.yml"), compose);
        
        // Generate .dockerignore
        String dockerignore = String.join("\n",
            "# Auto-generated by ConversationDocker CLI (W444)",
            "**/target/",
            "**/.gradle/",
            "**/build/",
            "**/.idea/",
            "**/*.iml",
            "**/data/conversations/*.ndjson",
            "**/data/exports/",
            "**/.vscode/",
            "**/.git/",
            "**/node_modules/",
            ""
        );
        Files.writeString(outDir.resolve(".dockerignore"), dockerignore);
        
        // Generate README
        String readme = String.join("\n",
            "# MATRIX Conversation Docker Setup",
            "",
            "Auto-generated by `ConversationDocker` (W444).",
            "",
            "## Files",
            "",
            "- `Dockerfile` - Image definition (Java 21 JRE + matrix-core jar + Qwen model)",
            "- `docker-compose.yml` - Service definition with port mappings and volumes",
            "- `.dockerignore` - Files to exclude from build context",
            "",
            "## Build",
            "",
            "```bash",
            "docker compose build",
            "```",
            "",
            "## Run",
            "",
            "```bash",
            "docker compose up -d",
            "```",
            "",
            "## Endpoints (after up)",
            "",
            "- `http://localhost:9093/` - Web UI",
            "- `http://localhost:9093/health` - Health check",
            "- `http://localhost:9093/chat` - Standard chat (POST JSON)",
            "- `http://localhost:9093/sessions` - List sessions",
            "- `http://localhost:9093/history?sessionId=X` - Session history",
            "- `http://localhost:9094/stream?msg=...` - Streaming SSE (different port)",
            "",
            "## Volumes",
            "",
            "- `conv-data` - Persists NDJSON conversation files",
            "- `conv-backup` - Mount point for zip backups",
            "",
            "## Verify",
            "",
            "```bash",
            "curl http://localhost:9093/health",
            "curl -X POST -H 'Content-Type: application/json' \\",
            "  -d '{\"message\":\"Hello\"}' http://localhost:9093/chat",
            "```",
            ""
        );
        Files.writeString(outDir.resolve("README.md"), readme);
        
        System.out.println("Generated Docker files in: " + outDir);
        System.out.println();
        System.out.println("Files created:");
        System.out.println("  - " + outDir.resolve("Dockerfile"));
        System.out.println("  - " + outDir.resolve("docker-compose.yml"));
        System.out.println("  - " + outDir.resolve(".dockerignore"));
        System.out.println("  - " + outDir.resolve("README.md"));
        System.out.println();
        System.out.println("Next steps:");
        System.out.println("  1. cd " + outDir);
        System.out.println("  2. cp ../../matrix-core/build/libs/matrix-core-1.0.0.jar build/libs/");
        System.out.println("  3. cp -r ../../models ./");
        System.out.println("  4. docker compose build");
        System.out.println("  5. docker compose up -d");
    }
}
