package io.matrix.consensus;

import io.matrix.hades.DerangementDetector;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Detects Byzantine faults in the consensus network.
 *
 * <p>Identifies three categories of Byzantine behavior:
 * <ul>
 * <li><b>Hallucinations</b> — nodes sending inconsistent payloads across rounds</li>
 * <li><b>Contradictions</b> — nodes voting against their own proposals</li>
 * <li><b>Equivocation</b> — nodes sending different values to different peers</li>
 * </ul>
 *
 * <p>Integrates with {@link DerangementDetector} for neuron-level anomaly detection,
 * bridging consensus-level and neuron-level fault domains.
 *
 * <p>Thread-safe: uses concurrent data structures for all mutable state.
 *
 * <p>Ref: arXiv:2410.16237 — fault detection heuristics
 */
public final class FaultDetector {

    public enum FaultType {
        HALLUCINATION, CONTRADICTION, EQUIVOCATION, NEURON_DERANGEMENT
    }

    public record FaultAlert(
            FaultType type,
            String nodeId,
            String description,
            long timestamp
    ) {}

    private final CopyOnWriteArrayList<FaultAlert> alerts;
    private final Map<String, List<ByzantineMessage>> messagesBySender;
    private final Map<String, Map<Integer, List<ByzantineMessage>>> votesBySenderAndRound;
    private final DerangementDetector derangementDetector;

    public FaultDetector() {
        this(new DerangementDetector());
    }

    public FaultDetector(DerangementDetector derangementDetector) {
        this.alerts = new CopyOnWriteArrayList<>();
        this.messagesBySender = new ConcurrentHashMap<>();
        this.votesBySenderAndRound = new ConcurrentHashMap<>();
        this.derangementDetector = Objects.requireNonNull(derangementDetector);
    }

    /**
     * Records a message and runs all fault detection heuristics.
     *
     * @return any fault alerts generated by this message
     */
    public List<FaultAlert> recordMessage(ByzantineMessage message) {
        messagesBySender.computeIfAbsent(message.senderId(),
                k -> new CopyOnWriteArrayList<>()).add(message);

        List<FaultAlert> newAlerts = new ArrayList<>();

        if (message.type() == ByzantineMessage.Type.VOTE
                || message.type() == ByzantineMessage.Type.COMMIT
                || message.type() == ByzantineMessage.Type.REJECT) {
            votesBySenderAndRound
                    .computeIfAbsent(message.senderId(), k -> new ConcurrentHashMap<>())
                    .computeIfAbsent(message.round(), k -> new CopyOnWriteArrayList<>())
                    .add(message);

            FaultAlert equivocation = checkEquivocation(message);
            if (equivocation != null) newAlerts.add(equivocation);
        }

        FaultAlert contradiction = checkContradiction(message);
        if (contradiction != null) newAlerts.add(contradiction);

        List<FaultAlert> hallucinations = checkHallucinations(message.senderId());
        newAlerts.addAll(hallucinations);

        alerts.addAll(newAlerts);
        return newAlerts;
    }

    /**
     * Checks for equivocation: same sender, same round, different agree values.
     */
    private FaultAlert checkEquivocation(ByzantineMessage message) {
        Map<Integer, List<ByzantineMessage>> rounds = votesBySenderAndRound.get(message.senderId());
        if (rounds == null) return null;

        List<ByzantineMessage> roundVotes = rounds.get(message.round());
        if (roundVotes == null || roundVotes.size() < 2) return null;

        boolean hasAgree = false;
        boolean hasDisagree = false;
        for (ByzantineMessage msg : roundVotes) {
            if (msg.agree()) hasAgree = true;
            else hasDisagree = true;
        }

        if (hasAgree && hasDisagree) {
            return new FaultAlert(FaultType.EQUIVOCATION, message.senderId(),
                    "Equivocation in round " + message.round()
                            + ": sent both agree and disagree",
                    System.currentTimeMillis());
        }
        return null;
    }

    /**
     * Checks for contradiction: node proposed a value but voted against it.
     */
    private FaultAlert checkContradiction(ByzantineMessage message) {
        if (message.type() != ByzantineMessage.Type.VOTE) return null;

        List<ByzantineMessage> senderMessages = messagesBySender.get(message.senderId());
        if (senderMessages == null) return null;

        for (ByzantineMessage msg : senderMessages) {
            if (msg.type() == ByzantineMessage.Type.PROPOSE
                    && msg.round() == message.round()
                    && !message.agree()) {
                return new FaultAlert(FaultType.CONTRADICTION, message.senderId(),
                        "Contradiction in round " + message.round()
                                + ": proposed '" + msg.payload() + "' but voted against",
                        System.currentTimeMillis());
            }
        }
        return null;
    }

    /**
     * Checks for hallucination: same sender, different payloads across rounds.
     */
    private List<FaultAlert> checkHallucinations(String senderId) {
        List<FaultAlert> result = new ArrayList<>();
        List<ByzantineMessage> senderMessages = messagesBySender.get(senderId);
        if (senderMessages == null || senderMessages.size() < 2) return result;

        String firstPayload = null;
        for (ByzantineMessage msg : senderMessages) {
            if (msg.type() == ByzantineMessage.Type.PROPOSE
                    || msg.type() == ByzantineMessage.Type.COMMIT) {
                if (firstPayload == null) {
                    firstPayload = msg.payload();
                } else if (!Objects.equals(firstPayload, msg.payload())) {
                    result.add(new FaultAlert(FaultType.HALLUCINATION, senderId,
                            "Hallucination: changed payload from '" + firstPayload
                                    + "' to '" + msg.payload() + "'",
                            System.currentTimeMillis()));
                    break;
                }
            }
        }
        return result;
    }

    /**
     * Returns a list of suspected node IDs based on accumulated fault alerts.
     */
    public List<String> suspectedNodes() {
        return alerts.stream()
                .map(FaultAlert::nodeId)
                .distinct()
                .toList();
    }

    /**
     * Checks if a specific node is suspected.
     */
    public boolean isSuspected(String nodeId) {
        return alerts.stream()
                .anyMatch(a -> a.nodeId().equals(nodeId));
    }

    /**
     * Returns the number of fault alerts for a specific node.
     */
    public int faultCount(String nodeId) {
        return (int) alerts.stream()
                .filter(a -> a.nodeId().equals(nodeId))
                .count();
    }

    /**
     * Returns all recorded alerts.
     */
    public List<FaultAlert> alerts() {
        return List.copyOf(alerts);
    }

    /**
     * Returns the underlying DerangementDetector for neuron-level analysis.
     */
    public DerangementDetector derangementDetector() {
        return derangementDetector;
    }

    /**
     * Clears all recorded alerts.
     */
    public void clear() {
        alerts.clear();
        messagesBySender.clear();
        votesBySenderAndRound.clear();
    }

    /**
     * Returns alerts filtered by fault type.
     */
    public List<FaultAlert> alertsByType(FaultType type) {
        return alerts.stream()
                .filter(a -> a.type() == type)
                .toList();
    }
}
