#!/usr/bin/env python3
"""
testbench_generator — Auto-generates Verilog testbenches for MPDT neurons.

Reads .ldn snapshot files and generates comprehensive testbenches that verify
all possible input combinations for each neuron.

Usage:
    python3 testbench_generator.py snapshot.ldn [output_dir]
    python3 testbench_generator.py --direct --k=4 --table=0x6A9C --name=xor4
"""

import json
import os
import sys
import argparse


def sanitize_verilog_identifier(name):
    result = []
    for c in name:
        if c.isalnum() or c == '_':
            result.append(c)
        else:
            result.append('_')
    return ''.join(result) or 'neuron'


def bitset_from_long_array(long_array, bit_count):
    bits = [False] * bit_count
    for word_idx, word in enumerate(long_array):
        base = word_idx * 64
        for bit in range(64):
            idx = base + bit
            if idx >= bit_count:
                break
            bits[idx] = (word >> bit) & 1 != 0
    return bits


def generate_testbench(name, k, bits):
    """Generate a Verilog testbench for an MPDT neuron."""
    safe_name = sanitize_verilog_identifier(name)
    module_name = f"mpdt_{safe_name}"
    tb_name = f"{module_name}_tb"
    num_entries = 1 << k
    table_bits = bits[:num_entries]

    # Count expected ones and zeros
    ones_count = sum(1 for b in table_bits if b)
    zeros_count = num_entries - ones_count

    verilog = f"""// Testbench for MPDT Neuron: {name}
// k = {k}, entries = {num_entries}
// Expected: {ones_count} ones, {zeros_count} zeros
// Auto-generated by testbench_generator.py

`timescale 1ns/1ps

module {tb_name};

    // Inputs
    reg [{k-1}:0] inputs;
    
    // Outputs
    wire output_;
    
    // Instantiate Unit Under Test (UUT)
    {module_name} uut (
        .inputs(inputs),
        .output_(output_)
    );
    
    // Test counters
    integer pass_count = 0;
    integer fail_count = 0;
    integer total_tests = 0;
    
    // Expected values
    reg [{num_entries-1}:0] expected;
    
    initial begin
        // Dump waveforms
        $dumpfile("{tb_name}.vcd");
        $dumpvars(0, {tb_name});
        
        // Initialize expected values from truth table
        expected = {num_entries}'b"""
    
    # Add expected bits (LSB first)
    for i in range(num_entries - 1, -1, -1):
        verilog += "1" if table_bits[i] else "0"
    
    verilog += f""";
        
        // Test all input combinations
        $display("=== Testing {module_name} ===");
        $display("Inputs | Expected | Actual | Status");
        $display("-------|----------|--------|-------");
        
        for (integer i = 0; i < {num_entries}; i = i + 1) begin
            inputs = i[{k-1}:0];
            #10; // Wait for propagation
            
            total_tests = total_tests + 1;
            
            if (output_ === expected[i]) begin
                pass_count = pass_count + 1;
                $display("%{k}b   |    %b     |   %b    | PASS", inputs, expected[i], output_);
            end else begin
                fail_count = fail_count + 1;
                $display("%{k}b   |    %b     |   %b    | FAIL", inputs, expected[i], output_);
            end
        end
        
        // Summary
        $display("");
        $display("=== Results ===");
        $display("Total:  %0d", total_tests);
        $display("Passed: %0d", pass_count);
        $display("Failed: %0d", fail_count);
        $display("Coverage: %0d%%", (pass_count * 100) / total_tests);
        
        if (fail_count == 0) begin
            $display("STATUS: ALL TESTS PASSED");
        end else begin
            $display("STATUS: %0d TESTS FAILED", fail_count);
        end
        
        $finish;
    end
    
    // Monitor for debugging
    initial begin
        $monitor("Time=%0t inputs=%b output_=%b", $time, inputs, output_);
    end

endmodule
"""
    return verilog


def generate_batch_testbench(neurons):
    """Generate a testbench that tests multiple neurons in sequence."""
    verilog = """// Batch testbench for multiple MPDT neurons
// Auto-generated by testbench_generator.py

`timescale 1ns/1ps

module matrix_batch_tb;

"""
    # Declare wires for each neuron
    for i, (name, k, bits) in enumerate(neurons):
        safe_name = sanitize_verilog_identifier(name)
        verilog += f"    reg [{k-1}:0] inputs_{i};\n"
        verilog += f"    wire output_{i};\n\n"

    # Instantiate all neurons
    for i, (name, k, bits) in enumerate(neurons):
        safe_name = sanitize_verilog_identifier(name)
        module_name = f"mpdt_{safe_name}"
        verilog += f"""    {module_name} neuron_{i} (
        .inputs(inputs_{i}),
        .output_(output_{i})
    );

"""

    verilog += """    integer total_pass = 0;
    integer total_fail = 0;

    initial begin
        $dumpfile("matrix_batch_tb.vcd");
        $dumpvars(0, matrix_batch_tb);
        
        $display("=== Matrix Batch Testbench ===");
        
"""

    # Test each neuron
    for i, (name, k, bits) in enumerate(neurons):
        safe_name = sanitize_verilog_identifier(name)
        module_name = f"mpdt_{safe_name}"
        num_entries = 1 << k
        table_bits = bits[:num_entries]
        
        verilog += f"        // Test {name} (k={k})\n"
        verilog += f'        $display("\\n--- Testing {module_name} ---");\n'
        
        for j in range(num_entries):
            expected = 1 if table_bits[j] else 0
            verilog += f"        inputs_{i} = {k}'d{j}; #10;\n"
            verilog += f"        if (output_{i} !== 1'b{expected}) begin\n"
            verilog += f'            $display("FAIL: inputs={k}\'b%b expected=1\'b{expected} got=1\'b%b", inputs_{i}, output_{i});\n'
            verilog += f"            total_fail = total_fail + 1;\n"
            verilog += f"        end else begin\n"
            verilog += f"            total_pass = total_pass + 1;\n"
            verilog += f"        end\n"

    verilog += """
        $display("");
        $display("=== Batch Results ===");
        $display("Total passed: %0d", total_pass);
        $display("Total failed: %0d", total_fail);
        
        if (total_fail == 0)
            $display("STATUS: ALL BATCH TESTS PASSED");
        else
            $display("STATUS: %0d BATCH TESTS FAILED", total_fail);
        
        $finish;
    end

endmodule
"""
    return verilog


def main():
    parser = argparse.ArgumentParser(description="MPDT neuron testbench generator")
    parser.add_argument("input", nargs="?", help=".ldn snapshot file path")
    parser.add_argument("output_dir", nargs="?", default=".", help="Output directory")
    parser.add_argument("-o", "--output-dir", dest="output_dir_opt",
                        help="Output directory (overrides positional)")
    parser.add_argument("--direct", action="store_true",
                        help="Generate single neuron directly")
    parser.add_argument("--k", type=int, default=4, help="Neuron input count")
    parser.add_argument("--table", type=str, default="0x6", help="Truth table hex")
    parser.add_argument("--name", type=str, default="custom", help="Neuron name")
    parser.add_argument("--batch", action="store_true",
                        help="Generate batch testbench for all neurons")
    args = parser.parse_args()

    output_dir = args.output_dir_opt if args.output_dir_opt else args.output_dir
    os.makedirs(output_dir, exist_ok=True)

    if args.direct:
        table_val = int(args.table, 16)
        bit_count = 1 << args.k
        bits = []
        for i in range(bit_count):
            bits.append((table_val >> i) & 1)
        
        verilog = generate_testbench(args.name, args.k, bits)
        safe_name = sanitize_verilog_identifier(args.name)
        out_path = os.path.join(output_dir, f"mpdt_{safe_name}_tb.v")
        with open(out_path, "w") as f:
            f.write(verilog)
        print(f"Generated: {out_path}")
        return

    if not args.input:
        parser.print_help()
        sys.exit(1)

    with open(args.input, "r") as f:
        snapshot = json.load(f)

    neurons_data = snapshot.get("neurons", [])
    if not neurons_data:
        print("No neurons found")
        sys.exit(1)

    neurons = []
    for record in neurons_data:
        name = record.get("neuronId", "unnamed")
        k = record.get("k", 2)
        truth_bits = record.get("truthTableBits", [0])
        bit_count = 1 << k
        bits = bitset_from_long_array(truth_bits, bit_count)
        neurons.append((name, k, bits))
        
        # Generate individual testbench
        verilog = generate_testbench(name, k, bits)
        safe_name = sanitize_verilog_identifier(name)
        out_path = os.path.join(output_dir, f"mpdt_{safe_name}_tb.v")
        with open(out_path, "w") as f:
            f.write(verilog)
        print(f"  Generated: {out_path}")

    # Generate batch testbench if requested
    if args.batch or len(neurons) > 1:
        batch_verilog = generate_batch_testbench(neurons)
        batch_path = os.path.join(output_dir, "matrix_batch_tb.v")
        with open(batch_path, "w") as f:
            f.write(batch_verilog)
        print(f"  Generated: {batch_path}")

    print(f"\nTotal: {len(neurons)} testbenches generated")


if __name__ == "__main__":
    main()
