apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - vpa.yaml
  - pvc.yaml
  - rbac.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - jaeger.yaml
  - loki.yaml
  - strimzi-kafka.yaml
  - minio-tenant.yaml
  - crd.yaml
  - cr-example.yaml

commonLabels:
  app.kubernetes.io/part-of: matrix
  app.kubernetes.io/version: v1.2.0
