apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - prometheus.yaml
  - grafana.yaml
  - matrix-core.yaml
