# MATRIX Core Native Image Properties — v2.1.0
# For GraalVM 25+ native-image builds
Args = -H:+ReportExceptionStackTraces \
       --enable-url-protocols=http,https \
       -H:ReflectionConfigurationResources=${.}/reflect-config.json \
       -H:ResourceConfigurationResources=${.}/resource-config.json \
       -H:+AddAllCharsets \
       --initialize-at-build-time=org.jboss.logmanager \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=io.netty \
       --initialize-at-build-time=com.fasterxml \
       --initialize-at-build-time=io.smallrye \
       --initialize-at-build-time=org.apache.avro \
       --initialize-at-run-time=io.matrix.cluster.NeuronClusterActor \
       --initialize-at-run-time=org.apache.pekko \
       --initialize-at-run-time=io.matrix.events.R2dbcEventJournal \
       --initialize-at-run-time=io.vertx.mutiny
